name: gencirc
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - dask
  - metpy
  - cartopy<0.25  # until the 0.25.1 release, https://github.com/scitools/cartopy/issues/2646
  - sympy
  - ffmpeg
  - climlab
  - numba
  - nc-time-axis
  - imagemagick
  - arraylake
  - pip
  - mystmd  # needed to rebuild the book from source
  - jupyterlab-myst
  - jupyterlab
  - pip:
    - pcodec
