name: gencirc
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - metpy
  - cartopy
  - sympy
  - ffmpeg
  - climlab
  - numba
  - nc-time-axis
  - imagemagick
  - mystmd  # needed to rebuild the book from source
  - jupyterlab-myst
  - jupyterlab
