name: gencirc
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - xarray
  - dask
  - metpy
  - cartopy
  - sympy
  - ffmpeg
  - climlab
  - numba
  - nc-time-axis
  - imagemagick
  - arraylake
  - pip
  - mystmd  # needed to rebuild the book from source
  - nodejs<26.8  # temporary pin due to bug
  - jupyterlab-myst
  - jupyterlab
  - pip:
    - pcodec
